-- dgGameMode
GAMEMODE_CRUISE         = 0 
GAMEMODE_CHECKPOINT     = 1
GAMEMODE_CNR            = 2
GAMEMODE_CIRCUIT        = 3
GAMEMODE_BLITZ          = 4
GAMEMODE_CROAM          = 5
GAMEMODE_CRASHCOURSE    = 6

--Time
TIME_MORNING = 0
TIME_NOON    = 1
TIME_EVENING = 2
TIME_NIGHT   = 3

-- Game state
STATE_RUNNING = -1
STATE_MENU = 0
STATE_GAME = 1

-- Game state (backwards compatibility)
STATE_UNKNOWN = -1

-- gfxDrawMode
DRAWMODE_POINTLIST      = 1
DRAWMODE_LINELIST       = 2
DRAWMODE_LINESTRIP      = 3
DRAWMODE_TRIANGLELIST   = 4
DRAWMODE_TRIANGLESTRIP  = 5
DRAWMODE_TRIANGLEFAN    = 6

-- rglToken
RGL_DEPTH_TEST = 0
RGL_CULL_FACE = 1
RGL_LIGHTING = 2
RGL_BLEND = 3

-- Bound Type
BOUNDTYPE_SPHERE        = 0
BOUNDTYPE_GEOMETRY      = 1
BOUNDTYPE_BOX           = 2 
BOUNDTYPE_FORCESPHERE   = 3
BOUNDTYPE_TERRAIN       = 4
BOUNDTYPE_TERRAINLOCAL  = 5
BOUNDTYPE_HOTDOG        = 6
BOUNDTYPE_LEVEL         = 7

-- Instance Flags
INST_ACTIVE             = 1
INST_COLLIDABLE         = 16
INST_DRIVABLE           = 32
INST_DRAW_SHADOW1       = 64
INST_DRAW_GLOW          = 128
INST_NOBACKFACING       = 256
INST_DRAW               = 512
INST_DRAW_SHADOW2       = 8192
INST_PLAYER             = 32768

-- dgPathType
PATHTYPE_POINTS         = 0
PATHTYPE_DIRECTED       = 1
PATHTYPE_LINESTRIP      = 2

-- gizBridgeType
BRIDGETYPE_INACTIVE     = 0
BRIDGETYPE_PROXIMITY    = 1
BRIDGETYPE_TIMED        = 2
BRIDGETYPE_ALWAYSOPEN   = 3

-- gizBridgeState
BRIDGESTATE_CLOSED      = 0
BRIDGESTATE_OPENING     = 1
BRIDGESTATE_OPEN        = 2
BRIDGESTATE_CLOSING     = 3

-- aiTrafficLightState
TRAFLITSTATE_NONE       = 0
TRAFLITSTATE_RED        = 1
TRAFLITSTATE_YELLOW     = 2
TRAFLITSTATE_GREEN      = 3
TRAFLITSTATE_WALK       = 4
TRAFLITSTATE_NOWALK     = 5

-- camViewCS / camTransitionCS TransitionType
TRANSITION_EASEIN       = 1
TRANSITION_EASEOUT      = 2
TRANSITION_EASEINOUT    = 3

-- aiMap ComponentType
AICOMPTYPE_NONE         = 0
AICOMPTYPE_ROAD         = 1
AICOMPTYPE_SHORTCUT     = 2
AICOMPTYPE_INTERSECTION = 3

-- Input device types
INPUTDEVICE_MOUSE      = 0
INPUTDEVICE_KEYBOARD   = 1
INPUTDEVICE_JOYSTICK   = 2
INPUTDEVICE_GAMEPAD    = 3
INPUTDEVICE_WHEEL2AXIS = 4

-- aiVehiclePhysicsState
AISTATE_FORWARD   = 0
AISTATE_BACKUP    = 1
AISTATE_SHORTCUT  = 2
AISTATE_STOP      = 3

-- aiPoliceState
AIPOLICESTATE_Idle          = 0
AIPOLICESTATE_Apprehend     = 1
AIPOLICESTATE_FollowPerp    = 2
AIPOLICESTATE_Invalid       = 5
AIPOLICESTATE_Incapacitated = 12

-- aiPoliceApprehendState
POLICEAPPREHENDSTATE_PushLeft  = 4
POLICEAPPREHENDSTATE_PushRight = 5
POLICEAPPREHENDSTATE_Block     = 6
POLICEAPPREHENDSTATE_BlockWait = 7

-- aiPath Flags
AIPATH_DIVIDED  = 0x1
AIPATH_ALLEYWAY = 0x2
AIPATH_FREEWAY  = 0x4
AIPATH_FLAT     = 0x8

-- mmWaypointObject Types
WPTYPE_CHECKPOINT = 0
WPTYPE_BILLBOARD  = 1
WPTYPE_POWERUP    = 2

-- mmHudMap Indicator Types
INDICATOR_RED_DOT     = 0
INDICATOR_BLUE_DOT    = 1
INDICATOR_GREEN_DOT   = 2
INDICATOR_GREY_DOT    = 3
INDICATOR_YELLOW_DOT  = 4
INDICATOR_FINISH_DOT  = 5
INDICATOR_GOLD_DOT    = 6
INDICATOR_BANK_DOT    = 7
INDICATOR_HIDEOUT_DOT = 8

-- CNR Game Modes
CNRMODE_FREEFORALL = 0
CNRMODE_COPSVROB   = 1
CNRMODE_TEAMS      = 2

-- CNR Limit Tpes
CNRLIMITTYPE_NONE  = 0
CNRLIMITTYPE_TIME  = 1
CNRLIMITTYPE_SCORE = 2

-- CNR Team IDs
CNRTEAM_BLUE    = 0
CNRTEAM_RED     = 1

CNRTEAM_COPS    = 0
CNRTEAM_ROBBERS = 1

-- Default Menu IDs
MENUID_MAIN             = 1
MENUID_OPTIONS          = 2
MENUID_AUDIOOPTIONS     = 3
MENUID_GFXOPTIONS       = 4
MENUID_CONTROLOPTIONS   = 5
MENUID_RACES            = 7
MENUID_VEHICLES         = 8
MENUID_SHOWCASE         = 9
MENUID_NETSELECT        = 10
MENUID_RACES_HOST       = 11
MENUID_NETARENA         = 12
MENUID_ABOUT            = 34
MENUID_CRASHCOURSE      = 39
MENUID_CRASHCOURSEINTRO = 40
MENUID_CONTROLCUSTOMIZE = 41

-- Default Menu Dialog IDs
DIALOGID_TCPIP               = 14
DIALOGID_SERIAL              = 16
DIALOGID_NEWPLAYER           = 17
DIALOGID_CONTROLASSIGN       = 21
DIALOGID_LOCKEDVEHICLEERROR  = 23

-- UITextField flags
TEXTFIELD_EDITABLE          = 0x1
TEXTFIELD_NOLABEL           = 0x2
TEXTFIELD_NOEDITCALLBACK    = 0x4
TEXTFIELD_LABELABOVE        = 0x10
TEXTFIELD_CLEARONBACKSPACE  = 0x20
TEXTFIELD_ALPHANUMERIC      = 0x40
TEXTFIELD_ESCAPECALLBACK    = 0x400