-- dgGameMode
GAMEMODE_CRUISE         = 0 
GAMEMODE_CHECKPOINT     = 1
GAMEMODE_CNR            = 2
GAMEMODE_CIRCUIT        = 3
GAMEMODE_BLITZ          = 4
GAMEMODE_CROAM          = 5
GAMEMODE_CRASHCOURSE    = 6

-- dgGameModeNames
GAMEMODE_NAMES = { [GAMEMODE_CRUISE] = "roam", [GAMEMODE_CHECKPOINT] = "race%d", [GAMEMODE_CNR] = "multicop", 
                   [GAMEMODE_CIRCUIT] = "circuit%d", [GAMEMODE_BLITZ] = "blitz%d", [GAMEMODE_CROAM] = "croam",
                   [GAMEMODE_CRASHCOURSE] = "crash%d" }

--Time
TIME_MORNING = 0
TIME_NOON    = 1
TIME_EVENING = 2
TIME_NIGHT   = 3

-- Game state
STATE_RUNNING = -1
STATE_MENU = 0
STATE_GAME = 1

-- Game state (backwards compatibility)
STATE_UNKNOWN = -1

-- gfxDrawMode
DRAWMODE_POINTLIST      = 1
DRAWMODE_LINELIST       = 2
DRAWMODE_LINESTRIP      = 3
DRAWMODE_TRIANGLELIST   = 4
DRAWMODE_TRIANGLESTRIP  = 5
DRAWMODE_TRIANGLEFAN    = 6

-- rglToken
RGL_DEPTH_TEST = 0
RGL_CULL_FACE = 1
RGL_LIGHTING = 2
RGL_BLEND = 3

-- Bound Type
BOUNDTYPE_SPHERE        = 0
BOUNDTYPE_GEOMETRY      = 1
BOUNDTYPE_BOX           = 2 
BOUNDTYPE_FORCESPHERE   = 3
BOUNDTYPE_TERRAIN       = 4
BOUNDTYPE_TERRAINLOCAL  = 5
BOUNDTYPE_HOTDOG        = 6
BOUNDTYPE_LEVEL         = 7

-- Instance Flags
INST_ACTIVE             = 1
INST_COLLIDABLE         = 16
INST_DRIVABLE           = 32
INST_DRAW_SHADOW1       = 64
INST_DRAW_GLOW          = 128
INST_NOBACKFACING       = 256
INST_DRAW               = 512
INST_STATIC             = 1024
INST_DRAW_SHADOW2       = 8192
INST_PLAYER             = 32768

-- Room flags
ROOM_SUBTERRANEAN       = 2
ROOM_WATER              = 4
ROOM_TRI_BOUND          = 32
ROOM_WARP               = 64

-- Vehicle flags
VEHICLE_COP             = 8
VEHICLE_LARGE           = 16
VEHICLE_RHD             = 64

-- dgPathType
PATHTYPE_POINTS         = 0
PATHTYPE_DIRECTED       = 1
PATHTYPE_LINESTRIP      = 2

-- gizBridgeType
BRIDGETYPE_INACTIVE     = 0
BRIDGETYPE_PROXIMITY    = 1
BRIDGETYPE_TIMED        = 2
BRIDGETYPE_ALWAYSOPEN   = 3

-- gizBridgeState
BRIDGESTATE_CLOSED      = 0
BRIDGESTATE_OPENING     = 1
BRIDGESTATE_OPEN        = 2
BRIDGESTATE_CLOSING     = 3

-- aiTrafficLightState
TRAFLITSTATE_NONE       = 0
TRAFLITSTATE_RED        = 1
TRAFLITSTATE_YELLOW     = 2
TRAFLITSTATE_GREEN      = 3
TRAFLITSTATE_WALK       = 4
TRAFLITSTATE_NOWALK     = 5

-- camViewCS / camTransitionCS TransitionType
TRANSITION_EASEIN       = 1
TRANSITION_EASEOUT      = 2
TRANSITION_EASEINOUT    = 3

-- aiMap ComponentType
AICOMPTYPE_NONE         = 0
AICOMPTYPE_ROAD         = 1
AICOMPTYPE_SHORTCUT     = 2
AICOMPTYPE_INTERSECTION = 3

-- Input device types
INPUTDEVICE_MOUSE      = 0
INPUTDEVICE_KEYBOARD   = 1
INPUTDEVICE_JOYSTICK   = 2
INPUTDEVICE_GAMEPAD    = 3
INPUTDEVICE_WHEEL2AXIS = 4

-- Mouse buttons
MOUSEBUTTON_LEFT   = 0
MOUSEBUTTON_RIGHT  = 1
MOUSEBUTTON_MIDDLE = 2

-- aiVehiclePhysicsState
AISTATE_FORWARD   = 0
AISTATE_BACKUP    = 1
AISTATE_SHORTCUT  = 2
AISTATE_STOP      = 3

-- aiPoliceState
POLICESTATE_IDLE          = 0
POLICESTATE_APPREHEND     = 1
POLICESTATE_FOLLOW        = 2
POLICESTATE_INVALID       = 5
POLICESTATE_INCAPACITATED = 12

-- aiPoliceApprehendState
APPREHENDSTATE_RAM       = 3
APPREHENDSTATE_PUSHLEFT  = 4
APPREHENDSTATE_PUSHRIGHT = 5
APPREHENDSTATE_BlOCK     = 6
APPREHENDSTATE_BLOCKWAIT = 7

-- aiPath Flags
AIPATH_DIVIDED  = 0x1
AIPATH_ALLEYWAY = 0x2
AIPATH_FREEWAY  = 0x4
AIPATH_FLAT     = 0x8

-- mmWaypointObject Types
WPTYPE_CHECKPOINT = 0
WPTYPE_BILLBOARD  = 1
WPTYPE_POWERUP    = 2

-- mmHudMap Indicator Types
INDICATOR_RED_DOT     = 0
INDICATOR_BLUE_DOT    = 1
INDICATOR_GREEN_DOT   = 2
INDICATOR_GREY_DOT    = 3
INDICATOR_YELLOW_DOT  = 4
INDICATOR_FINISH_DOT  = 5
INDICATOR_GOLD_DOT    = 6
INDICATOR_BANK_DOT    = 7
INDICATOR_HIDEOUT_DOT = 8

-- CNR Game Modes
CNRMODE_FREEFORALL = 0
CNRMODE_COPSVROB   = 1
CNRMODE_TEAMS      = 2

-- CNR Limit Tpes
CNRLIMITTYPE_NONE  = 0
CNRLIMITTYPE_TIME  = 1
CNRLIMITTYPE_SCORE = 2

-- CNR Team IDs
CNRTEAM_BLUE    = 0
CNRTEAM_RED     = 1

CNRTEAM_COPS    = 0
CNRTEAM_ROBBERS = 1

-- Audio Flags
AUDIOFLAG_SFX        = 0x1
AUDIOFLAG_MUSIC      = 0x4
AUDIOFLAG_STEREO     = 0x40
AUDIOFLAG_COMMENTARY = 0x400
AUDIOFLAG_AMBIENT    = 0x800

-- DirectMusic transition commands
DMUS_COMMANDT_GROOVE         = 0x0
DMUS_COMMANDT_FILL           = 0x1
DMUS_COMMANDT_INTRO          = 0x2
DMUS_COMMANDT_BREAK          = 0x3
DMUS_COMMANDT_END            = 0x4
DMUS_COMMANDT_ENDANDINTRO    = 0x5
  
-- DirectMusic compose flags
DMUS_COMPOSEF_NONE                = 0x0
DMUS_COMPOSEF_ALIGN               = 0x1
DMUS_COMPOSEF_OVERLAP             = 0x2
DMUS_COMPOSEF_IMMEDIATE           = 0x4
DMUS_COMPOSEF_GRID                = 0x8
DMUS_COMPOSEF_BEAT                = 0x10
DMUS_COMPOSEF_MEASURE             = 0x20
DMUS_COMPOSEF_AFTERPREPARETIME    = 0x40
DMUS_COMPOSEF_VALID_START_BEAT    = 0x80
DMUS_COMPOSEF_VALID_START_GRID    = 0x100
DMUS_COMPOSEF_VALID_START_TICK    = 0x200
DMUS_COMPOSEF_SEGMENTEND          = 0x400
DMUS_COMPOSEF_MARKER              = 0x800
DMUS_COMPOSEF_MODULATE            = 0x1000
DMUS_COMPOSEF_LONG                = 0x2000
DMUS_COMPOSEF_ENTIRE_TRANSITION   = 0x4000
DMUS_COMPOSEF_1BAR_TRANSITION     = 0x8000
DMUS_COMPOSEF_ENTIRE_ADDITION     = 0x10000
DMUS_COMPOSEF_1BAR_ADDITION       = 0x20000
DMUS_COMPOSEF_VALID_START_MEASURE = 0x40000
DMUS_COMPOSEF_DEFAULT             = 0x80000
DMUS_COMPOSEF_NOINVALIDATE        = 0x100000
DMUS_COMPOSEF_USE_AUDIOPATH       = 0x200000
DMUS_COMPOSEF_INVALIDATE_PRI      = 0x400000 

-- Default Menu IDs
MENUID_MAIN             = 1
MENUID_OPTIONS          = 2
MENUID_AUDIOOPTIONS     = 3
MENUID_GFXOPTIONS       = 4
MENUID_CONTROLOPTIONS   = 5
MENUID_RACES            = 7
MENUID_VEHICLES         = 8
MENUID_SHOWCASE         = 9
MENUID_NETSELECT        = 10
MENUID_RACES_HOST       = 11
MENUID_NETARENA         = 12
MENUID_ABOUT            = 34
MENUID_CRASHCOURSE      = 39
MENUID_CRASHCOURSEINTRO = 40
MENUID_CONTROLCUSTOMIZE = 41

-- Default Menu Dialog IDs
DIALOGID_TCPIP               = 14
DIALOGID_SERIAL              = 16
DIALOGID_NEWPLAYER           = 17
DIALOGID_CONTROLASSIGN       = 21
DIALOGID_LOCKEDVEHICLEERROR  = 23

-- UITextField flags
TEXTFIELD_EDITABLE          = 0x1
TEXTFIELD_NOLABEL           = 0x2
TEXTFIELD_NOEDITCALLBACK    = 0x4
TEXTFIELD_LABELABOVE        = 0x10
TEXTFIELD_CLEARONBACKSPACE  = 0x20
TEXTFIELD_ALPHANUMERIC      = 0x40
TEXTFIELD_ESCAPECALLBACK    = 0x400

-- Networking
DPID_ALL = 0

-- Veheicle Audio Types
VEHICLEAUDIO_PLAYER   = 0x0
VEHICLEAUDIO_OPPONENT = 0x1
VEHICLEAUDIO_NETWORK  = 0x2