-- dgGameMode
GAMEMODE_CRUISE         = 0 
GAMEMODE_CHECKPOINT     = 1
GAMEMODE_CNR            = 2
GAMEMODE_CIRCUIT        = 3
GAMEMODE_BLITZ          = 4
GAMEMODE_CROAM          = 5
GAMEMODE_CRASHCOURSE    = 6

-- gfxDrawMode
DRAWMODE_POINTLIST      = 1
DRAWMODE_LINELIST       = 2
DRAWMODE_LINESTRIP      = 3
DRAWMODE_TRIANGLELIST   = 4
DRAWMODE_TRIANGLESTRIP  = 5
DRAWMODE_TRIANGLEFAN    = 6

-- Bound Type
BOUNDTYPE_SPHERE        = 0
BOUNDTYPE_GEOMETRY      = 1
BOUNDTYPE_BOX           = 2
BOUNDTYPE_TERRAIN       = 4
BOUNDTYPE_TERRAINLOCAL  = 5
BOUNDTYPE_HOTDOG        = 6
BOUNDTYPE_LEVEL         = 7

-- Instance Flags
INST_DRIVABLE           = 32
INST_NOBACKFACING       = 256

-- dgPathType
PATHTYPE_POINTS         = 0
PATHTYPE_DIRECTED       = 1
PATHTYPE_LINESTRIP      = 2